### ISSUE TITLE
Issue on testing

### ISSUE THREAD

**Issue by Ecstaticvanilla** [Aaryan-Urunkar/DVote-India#3]
Same name candidates both get votes so instead of candidate name better to vote party name

I gave Modi,BJP and Modi,Congress and voted for Modi both won elections
___________________________________________________________________________________

NOTA option unavailable
___________________________________________________________________________________

**Comment by Aaryan-Urunkar** [comment]
Solved the name issue. The NOTA option part will be manually handled by election admin from client side
