### ISSUE TITLE
Issue with Date of Birth

### ISSUE THREAD

**Issue by Th3C0d3Mast3r** [Aaryan-Urunkar/DVote-India#5]
### ISSUE WITH DOB
We need to ensure two things:- 

- FIRSTLY, the date is correct(as in from 1 to 30, or 1 to 31 or even 1 to 28) for the respective months
- SECONDLY, the DOB should be such that, comparing to the DAY OF ELECTION KA DATE se one month back, the person must be atleast 18y/o

**Comment by Aaryan-Urunkar** [comment]
@CYCLOP5 ensure this is checked in the frontend

**Comment by Th3C0d3Mast3r** [comment]
Well, I was free and wrote its equivalent code in Java(and asked GPT to convert into JS, and here's the result)
@CYCLOP5 , just check whether its right or no-and if, then you could go ahead with this

### JS Code(converted by GPT, so do try out once)
<!DOCTYPE html>
<html>
<head>
    <title>Date of Birth Checker</title>
</head>
<body>
    <div id="app">
        <p>This is a code for Date Of Birth Checking.</p>
        <button onclick="run()">Press Any Key to proceed</button>
        <div id="input-section" style="display: none;">
            <p id="message"></p>
            <input type="number" id="date" placeholder="Enter the DATE">
            <br>
            <input type="number" id="month" placeholder="Enter the MONTH">
            <br>
            <input type="number" id="year" placeholder="Enter the YEAR">
            <br>
            <button onclick="checker()">Submit</button>
        </div>
        <div id="confirm-section" style="display: none;">
            <p id="dob-message"></p>
            <button onclick="reenter()">No, re-enter</button>
            <button onclick="nextFunction()">Yes</button>
        </div>
    </div>
    <script>
        function run() {
            document.getElementById('input-section').style.display = 'block';
        }

        function checker() {
            const date = parseInt(document.getElementById('date').value);
            const month = parseInt(document.getElementById('month').value);
            const year = parseInt(document.getElementById('year').value);

            if (isNaN(date) || isNaN(month) || isNaN(year)) {
                alert('Invalid input. Please enter numeric values.');
                return;
            }

            if (date > 31 || date < 1) {
                alert('Invalid Date-Retry');
                return;
            } else if (month > 12 || month < 1) {
                alert('Invalid Date-Retry');
                return;
            } else if (month == 2 && date > (isLeapYear(year) ? 29 : 28)) {
                alert('Invalid Date-Retry');
                return;
            } else if ((month == 4 || month == 6 || month == 9 || month == 11) && date > 30) {
                alert('Invalid Date-Retry');
                return;
            }

            document.getElementById('dob-message').innerText = "So, you entered the following DOB-is it correct? " + date + "/" + month + "/" + year + " (DD/MM/YYYY)";
            document.getElementById('input-section').style.display = 'none';
            document.getElementById('confirm-section').style.display = 'block';
        }

        function isLeapYear(year) {
            if (year % 4 !== 0) {
                return false;
            } else if (year % 100 !== 0) {
                return true;
            } else {
                return year % 400 === 0;
            }
        }

        function reenter() {
            document.getElementById('input-section').style.display = 'block';
            document.getElementById('confirm-section').style.display = 'none';
        }

        function nextFunction() {
            const date = document.getElementById('date').value;
            const month = document.getElementById('month').value;
            const year = document.getElementById('year').value;
            alert("Processing the date: " + date + "/" + month + "/" + year);
            document.getElementById('confirm-section').style.display = 'none';
        }
    </script>
</body>
</html>




### MY ORIGINAL CODE IN JAVA
import java.util.*;
public class dobChecker
{
    static Scanner obj=new Scanner(System.in);
    static String reply1="";
    static String reply2, reply3, reply4;
    public static void main(String args[])
    {
        run();
    }

    private static void run()
    {
        System.out.println("This is a code for Date Of Birth Checking.");
        System.out.println("Press Any Key to proceed");
        reply1=obj.nextLine();
        if(reply1!=null || reply1!="")
        {
            checker();
        }
        else
        {
            System.out.println("ERROR!");
            run();
        }
    }

    private static void checker() {
        System.out.print("\f");
        int datess = 0, monthss = 0, yearss = 0; // initially, they are all set to zero

        try {
            System.out.print("Enter the DATE: ");
            datess = obj.nextInt();

            System.out.print("\nEnter the MONTH: ");
            monthss = obj.nextInt();

            System.out.print("\nEnter the YEAR: ");
            yearss = obj.nextInt();

            obj.nextLine(); // Consume the newline character
        } catch (InputMismatchException e) {
            System.out.println("Invalid input. Please enter numeric values.");
            obj.next(); // Clear the invalid input
            checker();
            return;
        }

        if (datess > 31 || datess < 1) {
            System.out.println("Invalid Date-Retry");
            checker();
            return;
        } else if (monthss > 12 || monthss < 1) {
            System.out.println("Invalid Date-Retry");
            checker();
            return;
        } else if (monthss == 2 && datess > (isLeapYear(yearss) ? 29 : 28)) {
            System.out.println("Invalid Date-Retry");
            checker();
            return;
        } else if ((monthss == 4 || monthss == 6 || monthss == 9 || monthss == 11) && datess > 30) {
            System.out.println("Invalid Date-Retry");
            checker();
            return;
        }

        System.out.println("So, you entered the following DOB-is it correct?");
        System.out.println(datess + "/" + monthss + "/" + yearss + " (DD/MM/YYYY)");
        System.out.println("If no, then press \"N\" so as to re-enter");

        String reply2 = obj.nextLine();
        if (reply2.equalsIgnoreCase("N") || reply2.equalsIgnoreCase("nah") || reply2.equalsIgnoreCase("no")) {
            checker();
        } else {
            nextFunction(datess, monthss, yearss);
        }
    }

    private static boolean isLeapYear(int year) {
        if (year % 4 != 0) {
            return false;
        } else if (year % 100 != 0) {
            return true;
        } else {
            return year % 400 == 0;
        }
    }

    private static void nextFunction(int day, int month, int year) {
        // Placeholder for the next function to process the date
        System.out.println("\fProcessing the date: " + day + "/" + month + "/" + year);
    }
}
